import { test, expect } from '@playwright/test';

test('full multi-device round, locked answer, ranking, persistence, and voiding', async ({ page: host, context }) => {
  const failures: string[] = [];
  host.on('pageerror', error => failures.push(error.message));
  await host.goto('/host?demo=1');
  await host.getByRole('button', { name: 'Enter rehearsal host' }).click();
  await expect(host.getByRole('heading', { name: 'The control room.' })).toBeVisible();
  const stage = await context.newPage();
  stage.on('pageerror', error => failures.push(error.message));
  await stage.goto('/display?demo=1');
  await stage.getByRole('button', { name: 'Enable sound' }).click();
  const first = await context.newPage();
  first.on('pageerror', error => failures.push(error.message));
  await first.setViewportSize({ width: 390, height: 844 });
  await first.goto('/play?demo=1');
  await first.getByRole('button', { name: 'La Liga', exact: true }).click();
  await expect(first.locator('.player-ready').filter({ hasText: /^Ready$/ })).toBeVisible();
  const second = await context.newPage();
  await second.goto('/play?demo=1');
  await second.getByRole('button', { name: 'Ilustrados', exact: true }).click();
  await expect(second.locator('.player-ready').filter({ hasText: /^Ready$/ })).toBeVisible();

  await host.getByRole('button').filter({ hasText: 'In which town was José Rizal born?' }).click();
  await host.getByRole('button', { name: 'Prepare question' }).click();
  await expect(first.getByRole('heading', { name: 'You’re in.' })).toBeVisible();
  await expect(stage.getByRole('heading', { name: 'Ready?' })).toBeVisible();
  await host.getByRole('button', { name: 'Play', exact: true }).click();
  await expect(first.locator('.intro-tile')).toHaveCount(4);
  await expect(stage.locator('.intro-tile')).toHaveCount(4);
  await expect(first.getByRole('heading', { name: 'Choose.' })).toBeVisible({ timeout: 10_000 });
  await expect(first.getByText('In which town was José Rizal born?')).toHaveCount(0);
  await expect(stage.getByRole('heading', { name: 'In which town was José Rizal born?' })).toBeVisible();
  await first.getByRole('button', { name: /Calamba/ }).click();
  await expect(first.getByRole('heading', { name: 'Locked in.' })).toBeVisible();
  await second.waitForTimeout(300);
  await second.getByRole('button', { name: /Calamba/ }).click();
  await expect(second.getByRole('heading', { name: 'Locked in.' })).toBeVisible();
  await first.reload();
  await expect(first.getByRole('heading', { name: 'Locked in.' })).toBeVisible();
  await expect(host.getByText('2 of 4 groups answered')).toBeVisible();
  await expect(first.getByRole('heading', { name: 'Correct!' })).toBeVisible({ timeout: 30_000 });
  await expect(first.locator('.points-earned')).toContainText('+1000');
  await expect(second.locator('.points-earned')).toContainText('+900');
  await expect(stage.getByRole('heading', { name: 'La Liga', exact: true })).toBeVisible();
  await host.reload();
  await expect(host.getByRole('heading', { name: 'Round complete' })).toBeVisible();
  await expect(host.locator('.leaderboard').first()).toContainText('1,000');
  await host.getByRole('button', { name: 'Void result' }).click();
  await host.getByRole('button', { name: 'Confirm', exact: true }).click();
  await expect(first.getByRole('heading', { name: 'Round cancelled.' })).toBeVisible();
  await expect(first.locator('.player-points')).toContainText('0');
  expect(failures).toEqual([]);
});

test('question import, roster creation, and duplicate-device seat', async ({ page: host, context }) => {
  await host.goto('/host?demo=1');
  await host.getByRole('button', { name: 'Enter rehearsal host' }).click();
  await host.getByRole('button', { name: 'Setup', exact: true }).click();
  await host.getByRole('textbox', { name: 'Question bank JSON' }).fill(JSON.stringify([{ id: 'custom', prompt: 'Custom question?', section: 'Custom section', choices: ['Yes', 'No'], correctIndex: 0, explanation: 'An imported question.' }]));
  await host.getByRole('button', { name: 'Save question bank' }).click();
  await expect(host.getByRole('button').filter({ hasText: 'Custom question?' })).toBeVisible();
  await host.getByRole('textbox', { name: 'One group and email per line' }).fill('New Team, rep1@addu.edu.ph');
  await host.getByRole('button', { name: 'Create fresh session' }).click();
  await host.getByRole('button', { name: 'Confirm', exact: true }).click();
  const player = await context.newPage();
  await player.goto('/play?demo=1');
  await player.getByRole('button', { name: 'La Liga', exact: true }).click();
  await expect(player.getByText('New Team', { exact: true })).toBeVisible();
  await expect(player.locator('.player-ready').filter({ hasText: /^Ready$/ })).toBeVisible();
  const duplicate = await context.newPage();
  await duplicate.goto('/play?demo=1');
  await duplicate.getByRole('button', { name: 'La Liga', exact: true }).click();
  await expect(duplicate.getByText(/Another phone or tab is representing your group/)).toBeVisible();
  await host.getByRole('button', { name: 'Release New Team device' }).click();
  await duplicate.getByRole('button', { name: 'Rejoin on this phone' }).click();
  await expect(duplicate.locator('.player-ready').filter({ hasText: /^Ready$/ })).toBeVisible();
  await expect(player.getByText(/This device’s seat was released/)).toBeVisible();
  await duplicate.setViewportSize({ width: 360, height: 780 });
  const overflows = await duplicate.evaluate(() => document.documentElement.scrollWidth > window.innerWidth);
  expect(overflows).toBe(false);
});
